### ISSUE TITLE
[IMPROVEMENT] Android Data Binding Support

### ISSUE THREAD

**Issue by meness** [pinball83/Masked-Edittext#15]
Hi,

Please provide the `maskedText` property for supporting Android Data Binding. Currently setting `android:text` causes exception.

**Comment by javierpe** [comment]
Any solution?

**Comment by adigyran** [comment]
`java.lang.IndexOutOfBoundsException: setSpan (4 ... 4) ends beyond length 0
                                                                         at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1265)
                                                                         at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
                                                                         at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
                                                                         at android.text.Selection.setSelection(Selection.java:76)
                                                                         at android.text.Selection.setSelection(Selection.java:87)
                                                                         at android.widget.EditText.setSelection(EditText.java:103)
                                                                         at com.github.pinball83.maskededittext.MaskedEditText.onFocusChange(MaskedEditText.java:276)`
```
