### ISSUE TITLE
Mask gets deleted when entering special characters in a numeric MaskedEditText

### ISSUE THREAD

**Issue by sanjaygubaju** [pinball83/Masked-Edittext#28]
Special characters includes Spaces, Asterisk,Minus, Plus....... etc. Results in app crash...

**Comment by gmk57** [comment]
Crashes with IndexOutOfBoundsException. Example stack traces:

    java.lang.IndexOutOfBoundsException: charAt: 17 >= length 17
        at android.text.SpannableStringBuilder.charAt(SpannableStringBuilder.java:116)
        at com.github.pinball83.maskededittext.MaskedEditText.getUnmaskedText(MaskedEditText.java:206)
        at com.github.pinball83.maskededittext.MaskedEditText.onTouch(MaskedEditText.java:318)

    java.lang.IndexOutOfBoundsException: replace (8 ... 9) ends beyond length 8
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1018)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:460)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:454)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:33)
        at com.github.pinball83.maskededittext.MaskedEditText$MaskedInputFilter.filter(MaskedEditText.java:375)

    java.lang.IndexOutOfBoundsException: setSpan (7 ... 7) ends beyond length 6
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1018)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:611)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:607)
        at android.text.Selection.setSelection(Selection.java:76)
        at android.text.Selection.setSelection(Selection.java:87)
        at android.widget.EditText.setSelection(EditText.java:99)
        at com.github.pinball83.maskededittext.MaskedEditText$MaskedInputFilter.skipSymbol(MaskedEditText.java:421)
        at com.github.pinball83.maskededittext.MaskedEditText$MaskedInputFilter.filter(MaskedEditText.java:384)
